import fs from 'fs';
import path from 'path';

interface AudioEntry {
  file: string;
  duration?: number;
  voice?: string;
  sizeKB?: number;
}

// Generated by scripts/generate-audio.mjs. Read once per build worker.
let cached: Record<string, AudioEntry> | null = null;

export function getAudioForSlug(slug: string): AudioEntry | null {
  if (!cached) {
    try {
      cached = JSON.parse(
        fs.readFileSync(path.join(process.cwd(), 'public/audio/manifest.json'), 'utf8')
      );
    } catch {
      cached = {};
    }
  }
  return cached![slug] || null;
}
