import fs from 'fs';
import path from 'path';

interface AudioEntry {
  file: string;
  captions?: string;
  duration?: number;
  voice?: string;
  sizeKB?: number;
}

// Generated by scripts/generate-audio.mjs. Read once per build worker.
let cached: Record<string, AudioEntry> | null = null;

function load(): Record<string, AudioEntry> {
  if (!cached) {
    try {
      cached = JSON.parse(
        fs.readFileSync(path.join(process.cwd(), 'public/audio/manifest.json'), 'utf8')
      );
    } catch {
      cached = {};
    }
  }
  return cached!;
}

export function getAudioForSlug(slug: string): AudioEntry | null {
  return load()[slug] || null;
}

export function getNarratedSlugs(): string[] {
  return Object.keys(load());
}
