/**
 * QuantumShield WASM SDK — TypeScript Wrapper
 *
 * Post-quantum defense-in-depth encryption for the browser.
 *
 * @example
 * ```typescript
 * import { init, QShieldCipher, QShieldHybridKEM } from 'quantum-shield';
 *
 * // Initialize the WASM module (required before first use)
 * await init();
 *
 * // Symmetric encryption with Argon2id KDF
 * const cipher = new QShieldCipher('my-password');
 * const encrypted = cipher.encrypt_string('Hello, quantum world!');
 * const decrypted = cipher.decrypt_string(encrypted);
 *
 * // Post-quantum key exchange (X25519 + ML-KEM-768)
 * const alice = new QShieldHybridKEM();
 * const bob = new QShieldHybridKEM();
 * const encap = alice.encapsulate(bob.public_key);
 * const bobSecret = bob.decapsulate(encap.ciphertext);
 * // encap.shared_secret === bobSecret
 * ```
 *
 * @packageDocumentation
 */

// Re-export all types and classes from the WASM module.
// These are generated by wasm-bindgen during `wasm-pack build`.
import wasmInit, {
  QShieldCipher as WasmQShieldCipher,
  QShieldSession as WasmQShieldSession,
  QShieldKeyExchange as WasmQShieldKeyExchange,
  QShieldHybridKEM as WasmQShieldHybridKEM,
  QShieldSign as WasmQShieldSign,
  QShieldVerifier as WasmQShieldVerifier,
  DualSignature as WasmDualSignature,
  HybridEncapsulation as WasmHybridEncapsulation,
  HybridCipherResult as WasmHybridCipherResult,
  secure_compare,
  info,
  demo,
  benchmark,
  benchmark_hybrid_kem,
  benchmark_dual_signatures,
} from '../pkg/quantum_shield';

// Track initialization state
let initialized = false;
let initPromise: Promise<void> | null = null;

/**
 * Initialize the QuantumShield WASM module.
 *
 * Must be called once before using any other API. Subsequent calls are no-ops.
 * Safe to call multiple times — only the first call loads the module.
 *
 * @param wasmUrl - Optional URL or Response for the .wasm file (for custom loading)
 */
export async function init(
  wasmUrl?: string | URL | Request | Response | BufferSource | WebAssembly.Module
): Promise<void> {
  if (initialized) return;
  if (initPromise) return initPromise;

  initPromise = (async () => {
    await wasmInit(wasmUrl);
    initialized = true;
  })();

  return initPromise;
}

/** Check if the WASM module has been initialized. */
export function isInitialized(): boolean {
  return initialized;
}

// Re-export WASM classes with their original names
export {
  WasmQShieldCipher as QShieldCipher,
  WasmQShieldSession as QShieldSession,
  WasmQShieldKeyExchange as QShieldKeyExchange,
  WasmQShieldHybridKEM as QShieldHybridKEM,
  WasmQShieldSign as QShieldSign,
  WasmQShieldVerifier as QShieldVerifier,
  WasmDualSignature as DualSignature,
  WasmHybridEncapsulation as HybridEncapsulation,
  WasmHybridCipherResult as HybridCipherResult,
};

// Re-export utility functions
export {
  secure_compare,
  info,
  demo,
  benchmark,
  benchmark_hybrid_kem,
  benchmark_dual_signatures,
};

// Default export is the init function
export default init;
